---
title: "INFLUENCE OF THE 2016 NATIONAL GUIDELINE FOR THE PROVISION OF ADOLESCENT AND YOUTH FRIENDLY SERVICES IN REDUCING TEENAGE PREGNANCY IN SIAYA COUNTY"
format: html
editor: visual
bibliography: references.bib
---

### Acronyms and Abbreviations

AYFS Adolescent and Youth Friendly Services

AYSRH Adolescent and Youth friendly Sexual Reproductive Health Services

HIV Human Immuno-deficiency Virus

KDHS Kenya Demographic Health Survey

MOH Ministry of Health

SRH Sexual and Reproductive Health

WHO World Health organization

### Definition of Terms

Adolescent: Person aged between 10 - 19 years old.

Health: Complete physical, mental and social well-being.

Teenager: Person aged between 13 - 19 years old.

Young people: Persons aged between 10 - 24 years as defined by WHO.

Youth: Persons aged between 10 - 24 years as defined by WHO.

For the purpose of this study, the terms will be used according to these definitions. The terms youth and young people are used interchangably.

## Introduction

### Background

Teenage pregnancy is a subject of interest not only because of the social implications it has for the young people who make up a significant proportion of the population but also because of the medical implications it has as elucidated in studies like @boia2016medical. The MOH came up with the 2016 National Guideline for the provision of AYFS in a bid to improve SRH health services especially for the youth. Considering the importance of teenage pregnancy, it is imperative to evaluate the progress that has been made so far since this document came into place. It is noteworthy that there has not been research into the impact that the 2016 National Guideline for provision of AYFS has had on teenage pregnancy to be specific at Siaya county and even at the National level.

One of the methods of ascertaining this progress is by relying on the data provided periodically by the KDHS on childbearing by girls between the age of 15 - 19 years old. It should however be noted that this age bracket ignores a significant portion of the population of girls below the age of 15 years old who have also reported a lot of pregnancy cases. Because of this unaccounted segment of the population, it is not sufficient to rely on the KDHS data which only accounts for pregnancies for teenagers between the age of 15 - 19 years. Additionally, it is important to discern the impact that this document has had in Siaya county given that Siaya county has its own unique challenges.

This study investigates the influence of the 2016 National Guideline for the Provision of AYFS in reducing teenage pregnancy in Siaya county among those between the age of 13 - 19 years by conducting qualitative studies targeting a sample of key stakeholders like medics, parents and also girls between the ages of 13 - 19 years old. The results from this study will give a clearer picture to the stakeholders regarding the influence this document has had in regards to teenage pregnancy; the information that teenagers have about comprehensive sexual and reproductive health and consequently put forward measures to address the gaps that exist to address teenage pregnancy in Siaya county. Also, this study will inform targeted intervention programs to reduce teenage pregnancies in Siaya county.

### Justification for the study.

KDHS(2022) has shown that, in Siaya county, 20.9% of the girls aged between 15 - 19 years old had begun child bearing. This figure is higher than 17.2% which was reported by KDHS(2014) thus raising fears over the effectiveness of the National Guidelines for Provision of Adolescent Youth-Friendly Guidelines (2016) in containing teenage pregnancies.

This study therefore aims to establish the effectiveness of this guideline with respect to teenage pregnancy; assess knowledge of teenagers on comprehensive SRH information and suggest measures to address gaps in order to reduce teenage pregnancies which seems to be on an upward trend in Siaya county.

### Purpose of the study

#### Objectives

1.  To establish the effectiveness of adolescents and youth friendly services for addressing teenage pregnancy in Siaya county.
2.  To assess the knowledge of comprehensive sexual and reproductive health information services amongst teenagers in Siaya county.
3.  To suggest measures for addressing gaps in reducing teenage pregnancy in Siaya county.

## Literature Review.

Teenage pregnancy, defined as pregnancy in girls between the ages of 13 - 19 years continues to be a challenge in Siaya county and even in Kenya. Over the years, there has been a raft of measures and interventions intended at reducing teenage pregnancy in Kenya by the MOH, county governments and also by partners both at national and sub-national level.One of the most notable measures was the coming to life of the National Guidelines for Provision of AYFS in Kenya, 2016. This was an attempt at addressing among other reproductive issues, the issue of teenage pregnancy by aligning AYSRH provision in Kenya to international standards.

One of the objectives of the National Guidelines for Provision of Adolescent and Youth Friendly Services in Kenya, 2016 was to standardize the provision of quality AYSRH Services at all levels by ensuring reproductive health service provision for adolescents and youth are equitable; accessible; acceptable; appropriate and effective as outlined in @World2019. This would then, among other things, translate to a reduction in teenage pregnancies. A study in Western Kenya by @wafula2022 investigating the availability and readiness of health facilities to deliver sexual and reproductive health services for young people found that only a small proportion of healthcare personnel providing AYSRH to young people have actually received training on the same. This lack of training for healthcare personnel on AYSRH makes the Guideline less likely to achieve its objectives because of lack of skills by the service providers to handle young people appropriately. Having conducted the study in the larger Western Kenya, the results by @wafula2022 may not mirror the true picture in Siaya county because healthcare is a devolved function and thus disparities do exist across the counties. This gap necessitates an evaluation Siaya county independent of the other counties.

The second objective of the National Guidelines for Provision of AYFS in Kenya, 2016 - defining the essential package of health services to be provided to adolescents and youth at service delivery points; @ochieng2022 investigating availability and readiness of health facilities to deliver AYSRH for young people in Western Kenya, including Siaya county, established that only a quarter (26%) of the total personnel surveyed were trained on youth-friendly services; up to 17% of the health facilities did not provide information on SRH services and this means that young people are not aware of the available services. The same report also found that almost half (47.83%) of the health facilities surveyed had no plan of conducting outreach for young people, which is an important ingredient in getting services to the most vulnerable teenagers according to @denno2015. There is therefore potentially a chance that some youth are unaware of the available services because of these gaps. Additionally, the result of this investigation was a generalization of the larger Western Kenya and not Siaya county specifically, consequently, it is not possible to get a clear picture of the influence that the National Guideline for provision of adolescent and youth friendly services, 2016 has had in Siaya county from this investigation.

The other key objective of the National Guidelines for Provision of Adolescent and Youth Friendly Services in Kenya, 2016 - increasing access to comprehensive sexual and reproductive health information and services among adolescents and youth, appears to have been achieved; @Tshombe2020 while investigating Utilization of adolescent reproductive health services in Bondo sub-county, Siaya county found that majority of teenagers have received information on Reproductive health in their schools thus implying that teenagers are aware of sexual and reproductive health information. This finding does not however necessarily apply to the entire Siaya county as it was only limited to Bondo sub-county thus necessitating an investigation on the entire Siaya county.

Despite the positive progress reported by various studies, the KDHS(2014) and KDHS(2022) indicated that 17.2% and 20.9% of girls between 15 - 19 years respectively had begun child bearing in Siaya county. This upward trend casts aspersions on the effectiveness of the 2016 National Guidelines for Provision of Adolescent and Youth Friendly Services in Kenya in reducing teenage pregnancies in Siaya county. However, it should be noted that this statistic did not include the entire age bracket that defines teenagers, 13 - 19 years old. As such, it cannot be concluded whether or not the 2016 National Guidelines for Provision of Adolescent and Youth Friendly Services in Kenya was effective in reducing teenage pregnancies in with regard to Siaya county.
